include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/.dart_tool/**"
    - "**/build/**"

linter:
  rules:
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    use_super_parameters: true
    unnecessary_lambdas: true
    sort_constructors_first: true
