name: feature_reports
description: "Modulo Flutter de reportes operativos."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  design_system:
    path: ../design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
resolution: workspace


